// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage/pubgh"
)

// NewMockReleaseReader creates a new instance of MockReleaseReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReleaseReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReleaseReader {
	mock := &MockReleaseReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReleaseReader is an autogenerated mock type for the ReleaseReader type
type MockReleaseReader struct {
	mock.Mock
}

type MockReleaseReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReleaseReader) EXPECT() *MockReleaseReader_Expecter {
	return &MockReleaseReader_Expecter{mock: &_m.Mock}
}

// FindDraft provides a mock function for the type MockReleaseReader
func (_mock *MockReleaseReader) FindDraft(ctx context.Context, repository pubgh.Repository, tag rel.Tag) (pubgh.Release, error) {
	ret := _mock.Called(ctx, repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for FindDraft")
	}

	var r0 pubgh.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, rel.Tag) (pubgh.Release, error)); ok {
		return returnFunc(ctx, repository, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, rel.Tag) pubgh.Release); ok {
		r0 = returnFunc(ctx, repository, tag)
	} else {
		r0 = ret.Get(0).(pubgh.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubgh.Repository, rel.Tag) error); ok {
		r1 = returnFunc(ctx, repository, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReleaseReader_FindDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDraft'
type MockReleaseReader_FindDraft_Call struct {
	*mock.Call
}

// FindDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubgh.Repository
//   - tag rel.Tag
func (_e *MockReleaseReader_Expecter) FindDraft(ctx any, repository any, tag any) *MockReleaseReader_FindDraft_Call {
	return &MockReleaseReader_FindDraft_Call{Call: _e.mock.On("FindDraft", ctx, repository, tag)}
}

func (_c *MockReleaseReader_FindDraft_Call) Run(run func(ctx context.Context, repository pubgh.Repository, tag rel.Tag)) *MockReleaseReader_FindDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubgh.Repository
		if args[1] != nil {
			arg1 = args[1].(pubgh.Repository)
		}
		var arg2 rel.Tag
		if args[2] != nil {
			arg2 = args[2].(rel.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReleaseReader_FindDraft_Call) Return(release pubgh.Release, err error) *MockReleaseReader_FindDraft_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *MockReleaseReader_FindDraft_Call) RunAndReturn(run func(ctx context.Context, repository pubgh.Repository, tag rel.Tag) (pubgh.Release, error)) *MockReleaseReader_FindDraft_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockReleaseReader
func (_mock *MockReleaseReader) Get(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID) (pubgh.Release, error) {
	ret := _mock.Called(ctx, repository, release)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 pubgh.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) (pubgh.Release, error)); ok {
		return returnFunc(ctx, repository, release)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) pubgh.Release); ok {
		r0 = returnFunc(ctx, repository, release)
	} else {
		r0 = ret.Get(0).(pubgh.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) error); ok {
		r1 = returnFunc(ctx, repository, release)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReleaseReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReleaseReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubgh.Repository
//   - release pubgh.ReleaseID
func (_e *MockReleaseReader_Expecter) Get(ctx any, repository any, release any) *MockReleaseReader_Get_Call {
	return &MockReleaseReader_Get_Call{Call: _e.mock.On("Get", ctx, repository, release)}
}

func (_c *MockReleaseReader_Get_Call) Run(run func(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID)) *MockReleaseReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubgh.Repository
		if args[1] != nil {
			arg1 = args[1].(pubgh.Repository)
		}
		var arg2 pubgh.ReleaseID
		if args[2] != nil {
			arg2 = args[2].(pubgh.ReleaseID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReleaseReader_Get_Call) Return(release1 pubgh.Release, err error) *MockReleaseReader_Get_Call {
	_c.Call.Return(release1, err)
	return _c
}

func (_c *MockReleaseReader_Get_Call) RunAndReturn(run func(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID) (pubgh.Release, error)) *MockReleaseReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// WaitAssets provides a mock function for the type MockReleaseReader
func (_mock *MockReleaseReader) WaitAssets(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID) (pubgh.AssetsView, error) {
	ret := _mock.Called(ctx, repository, release)

	if len(ret) == 0 {
		panic("no return value specified for WaitAssets")
	}

	var r0 pubgh.AssetsView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) (pubgh.AssetsView, error)); ok {
		return returnFunc(ctx, repository, release)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) pubgh.AssetsView); ok {
		r0 = returnFunc(ctx, repository, release)
	} else {
		r0 = ret.Get(0).(pubgh.AssetsView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubgh.Repository, pubgh.ReleaseID) error); ok {
		r1 = returnFunc(ctx, repository, release)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReleaseReader_WaitAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitAssets'
type MockReleaseReader_WaitAssets_Call struct {
	*mock.Call
}

// WaitAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubgh.Repository
//   - release pubgh.ReleaseID
func (_e *MockReleaseReader_Expecter) WaitAssets(ctx any, repository any, release any) *MockReleaseReader_WaitAssets_Call {
	return &MockReleaseReader_WaitAssets_Call{Call: _e.mock.On("WaitAssets", ctx, repository, release)}
}

func (_c *MockReleaseReader_WaitAssets_Call) Run(run func(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID)) *MockReleaseReader_WaitAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubgh.Repository
		if args[1] != nil {
			arg1 = args[1].(pubgh.Repository)
		}
		var arg2 pubgh.ReleaseID
		if args[2] != nil {
			arg2 = args[2].(pubgh.ReleaseID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReleaseReader_WaitAssets_Call) Return(assetsView pubgh.AssetsView, err error) *MockReleaseReader_WaitAssets_Call {
	_c.Call.Return(assetsView, err)
	return _c
}

func (_c *MockReleaseReader_WaitAssets_Call) RunAndReturn(run func(ctx context.Context, repository pubgh.Repository, release pubgh.ReleaseID) (pubgh.AssetsView, error)) *MockReleaseReader_WaitAssets_Call {
	_c.Call.Return(run)
	return _c
}
