// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pubbrew"
)

// NewMockRepositoryWriter creates a new instance of MockRepositoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryWriter {
	mock := &MockRepositoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryWriter is an autogenerated mock type for the RepositoryWriter type
type MockRepositoryWriter struct {
	mock.Mock
}

type MockRepositoryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryWriter) EXPECT() *MockRepositoryWriter_Expecter {
	return &MockRepositoryWriter_Expecter{mock: &_m.Mock}
}

// CreateBranch provides a mock function for the type MockRepositoryWriter
func (_mock *MockRepositoryWriter) CreateBranch(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, from pubbrew.CommitSHA) error {
	ret := _mock.Called(ctx, repository, branch, from)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.CommitSHA) error); ok {
		r0 = returnFunc(ctx, repository, branch, from)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWriter_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockRepositoryWriter_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - branch pubbrew.BranchName
//   - from pubbrew.CommitSHA
func (_e *MockRepositoryWriter_Expecter) CreateBranch(ctx any, repository any, branch any, from any) *MockRepositoryWriter_CreateBranch_Call {
	return &MockRepositoryWriter_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, repository, branch, from)}
}

func (_c *MockRepositoryWriter_CreateBranch_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, from pubbrew.CommitSHA)) *MockRepositoryWriter_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.BranchName
		if args[2] != nil {
			arg2 = args[2].(pubbrew.BranchName)
		}
		var arg3 pubbrew.CommitSHA
		if args[3] != nil {
			arg3 = args[3].(pubbrew.CommitSHA)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoryWriter_CreateBranch_Call) Return(err error) *MockRepositoryWriter_CreateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWriter_CreateBranch_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, from pubbrew.CommitSHA) error) *MockRepositoryWriter_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function for the type MockRepositoryWriter
func (_mock *MockRepositoryWriter) CreatePullRequest(ctx context.Context, repository pubbrew.Repository, input pubbrew.PullRequestInput) (string, error) {
	ret := _mock.Called(ctx, repository, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.PullRequestInput) (string, error)); ok {
		return returnFunc(ctx, repository, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.PullRequestInput) string); ok {
		r0 = returnFunc(ctx, repository, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubbrew.Repository, pubbrew.PullRequestInput) error); ok {
		r1 = returnFunc(ctx, repository, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryWriter_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockRepositoryWriter_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - input pubbrew.PullRequestInput
func (_e *MockRepositoryWriter_Expecter) CreatePullRequest(ctx any, repository any, input any) *MockRepositoryWriter_CreatePullRequest_Call {
	return &MockRepositoryWriter_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, repository, input)}
}

func (_c *MockRepositoryWriter_CreatePullRequest_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, input pubbrew.PullRequestInput)) *MockRepositoryWriter_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.PullRequestInput
		if args[2] != nil {
			arg2 = args[2].(pubbrew.PullRequestInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryWriter_CreatePullRequest_Call) Return(s string, err error) *MockRepositoryWriter_CreatePullRequest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepositoryWriter_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, input pubbrew.PullRequestInput) (string, error)) *MockRepositoryWriter_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// PutFile provides a mock function for the type MockRepositoryWriter
func (_mock *MockRepositoryWriter) PutFile(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath, previous pubbrew.BlobSHA, content []byte, message string) error {
	ret := _mock.Called(ctx, repository, branch, path, previous, content, message)

	if len(ret) == 0 {
		panic("no return value specified for PutFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.FilePath, pubbrew.BlobSHA, []byte, string) error); ok {
		r0 = returnFunc(ctx, repository, branch, path, previous, content, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWriter_PutFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutFile'
type MockRepositoryWriter_PutFile_Call struct {
	*mock.Call
}

// PutFile is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - branch pubbrew.BranchName
//   - path pubbrew.FilePath
//   - previous pubbrew.BlobSHA
//   - content []byte
//   - message string
func (_e *MockRepositoryWriter_Expecter) PutFile(ctx any, repository any, branch any, path any, previous any, content any, message any) *MockRepositoryWriter_PutFile_Call {
	return &MockRepositoryWriter_PutFile_Call{Call: _e.mock.On("PutFile", ctx, repository, branch, path, previous, content, message)}
}

func (_c *MockRepositoryWriter_PutFile_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath, previous pubbrew.BlobSHA, content []byte, message string)) *MockRepositoryWriter_PutFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.BranchName
		if args[2] != nil {
			arg2 = args[2].(pubbrew.BranchName)
		}
		var arg3 pubbrew.FilePath
		if args[3] != nil {
			arg3 = args[3].(pubbrew.FilePath)
		}
		var arg4 pubbrew.BlobSHA
		if args[4] != nil {
			arg4 = args[4].(pubbrew.BlobSHA)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockRepositoryWriter_PutFile_Call) Return(err error) *MockRepositoryWriter_PutFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWriter_PutFile_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath, previous pubbrew.BlobSHA, content []byte, message string) error) *MockRepositoryWriter_PutFile_Call {
	_c.Call.Return(run)
	return _c
}
