// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pubbrew"
)

// NewMockRepositoryReader creates a new instance of MockRepositoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryReader {
	mock := &MockRepositoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryReader is an autogenerated mock type for the RepositoryReader type
type MockRepositoryReader struct {
	mock.Mock
}

type MockRepositoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryReader) EXPECT() *MockRepositoryReader_Expecter {
	return &MockRepositoryReader_Expecter{mock: &_m.Mock}
}

// ReadBase provides a mock function for the type MockRepositoryReader
func (_mock *MockRepositoryReader) ReadBase(ctx context.Context, repository pubbrew.Repository, path pubbrew.FilePath) (pubbrew.BaseSnapshot, error) {
	ret := _mock.Called(ctx, repository, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadBase")
	}

	var r0 pubbrew.BaseSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.FilePath) (pubbrew.BaseSnapshot, error)); ok {
		return returnFunc(ctx, repository, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.FilePath) pubbrew.BaseSnapshot); ok {
		r0 = returnFunc(ctx, repository, path)
	} else {
		r0 = ret.Get(0).(pubbrew.BaseSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubbrew.Repository, pubbrew.FilePath) error); ok {
		r1 = returnFunc(ctx, repository, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryReader_ReadBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBase'
type MockRepositoryReader_ReadBase_Call struct {
	*mock.Call
}

// ReadBase is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - path pubbrew.FilePath
func (_e *MockRepositoryReader_Expecter) ReadBase(ctx any, repository any, path any) *MockRepositoryReader_ReadBase_Call {
	return &MockRepositoryReader_ReadBase_Call{Call: _e.mock.On("ReadBase", ctx, repository, path)}
}

func (_c *MockRepositoryReader_ReadBase_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, path pubbrew.FilePath)) *MockRepositoryReader_ReadBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.FilePath
		if args[2] != nil {
			arg2 = args[2].(pubbrew.FilePath)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryReader_ReadBase_Call) Return(baseSnapshot pubbrew.BaseSnapshot, err error) *MockRepositoryReader_ReadBase_Call {
	_c.Call.Return(baseSnapshot, err)
	return _c
}

func (_c *MockRepositoryReader_ReadBase_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, path pubbrew.FilePath) (pubbrew.BaseSnapshot, error)) *MockRepositoryReader_ReadBase_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBranch provides a mock function for the type MockRepositoryReader
func (_mock *MockRepositoryReader) ReadBranch(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath) (pubbrew.BranchSnapshot, error) {
	ret := _mock.Called(ctx, repository, branch, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadBranch")
	}

	var r0 pubbrew.BranchSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.FilePath) (pubbrew.BranchSnapshot, error)); ok {
		return returnFunc(ctx, repository, branch, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.FilePath) pubbrew.BranchSnapshot); ok {
		r0 = returnFunc(ctx, repository, branch, path)
	} else {
		r0 = ret.Get(0).(pubbrew.BranchSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.FilePath) error); ok {
		r1 = returnFunc(ctx, repository, branch, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryReader_ReadBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBranch'
type MockRepositoryReader_ReadBranch_Call struct {
	*mock.Call
}

// ReadBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - branch pubbrew.BranchName
//   - path pubbrew.FilePath
func (_e *MockRepositoryReader_Expecter) ReadBranch(ctx any, repository any, branch any, path any) *MockRepositoryReader_ReadBranch_Call {
	return &MockRepositoryReader_ReadBranch_Call{Call: _e.mock.On("ReadBranch", ctx, repository, branch, path)}
}

func (_c *MockRepositoryReader_ReadBranch_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath)) *MockRepositoryReader_ReadBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.BranchName
		if args[2] != nil {
			arg2 = args[2].(pubbrew.BranchName)
		}
		var arg3 pubbrew.FilePath
		if args[3] != nil {
			arg3 = args[3].(pubbrew.FilePath)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoryReader_ReadBranch_Call) Return(branchSnapshot pubbrew.BranchSnapshot, err error) *MockRepositoryReader_ReadBranch_Call {
	_c.Call.Return(branchSnapshot, err)
	return _c
}

func (_c *MockRepositoryReader_ReadBranch_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, branch pubbrew.BranchName, path pubbrew.FilePath) (pubbrew.BranchSnapshot, error)) *MockRepositoryReader_ReadBranch_Call {
	_c.Call.Return(run)
	return _c
}

// ReadPullRequest provides a mock function for the type MockRepositoryReader
func (_mock *MockRepositoryReader) ReadPullRequest(ctx context.Context, repository pubbrew.Repository, base pubbrew.BranchName, head pubbrew.BranchName) (pubbrew.PullRequest, error) {
	ret := _mock.Called(ctx, repository, base, head)

	if len(ret) == 0 {
		panic("no return value specified for ReadPullRequest")
	}

	var r0 pubbrew.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.BranchName) (pubbrew.PullRequest, error)); ok {
		return returnFunc(ctx, repository, base, head)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.BranchName) pubbrew.PullRequest); ok {
		r0 = returnFunc(ctx, repository, base, head)
	} else {
		r0 = ret.Get(0).(pubbrew.PullRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubbrew.Repository, pubbrew.BranchName, pubbrew.BranchName) error); ok {
		r1 = returnFunc(ctx, repository, base, head)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryReader_ReadPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadPullRequest'
type MockRepositoryReader_ReadPullRequest_Call struct {
	*mock.Call
}

// ReadPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubbrew.Repository
//   - base pubbrew.BranchName
//   - head pubbrew.BranchName
func (_e *MockRepositoryReader_Expecter) ReadPullRequest(ctx any, repository any, base any, head any) *MockRepositoryReader_ReadPullRequest_Call {
	return &MockRepositoryReader_ReadPullRequest_Call{Call: _e.mock.On("ReadPullRequest", ctx, repository, base, head)}
}

func (_c *MockRepositoryReader_ReadPullRequest_Call) Run(run func(ctx context.Context, repository pubbrew.Repository, base pubbrew.BranchName, head pubbrew.BranchName)) *MockRepositoryReader_ReadPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubbrew.Repository
		if args[1] != nil {
			arg1 = args[1].(pubbrew.Repository)
		}
		var arg2 pubbrew.BranchName
		if args[2] != nil {
			arg2 = args[2].(pubbrew.BranchName)
		}
		var arg3 pubbrew.BranchName
		if args[3] != nil {
			arg3 = args[3].(pubbrew.BranchName)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepositoryReader_ReadPullRequest_Call) Return(pullRequest pubbrew.PullRequest, err error) *MockRepositoryReader_ReadPullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockRepositoryReader_ReadPullRequest_Call) RunAndReturn(run func(ctx context.Context, repository pubbrew.Repository, base pubbrew.BranchName, head pubbrew.BranchName) (pubbrew.PullRequest, error)) *MockRepositoryReader_ReadPullRequest_Call {
	_c.Call.Return(run)
	return _c
}
