// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/image"
)

// NewMockComposer creates a new instance of MockComposer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComposer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComposer {
	mock := &MockComposer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComposer is an autogenerated mock type for the Composer type
type MockComposer struct {
	mock.Mock
}

type MockComposer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComposer) EXPECT() *MockComposer_Expecter {
	return &MockComposer_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockComposer
func (_mock *MockComposer) Build(ctx context.Context, request image.ComposeRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.ComposeRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComposer_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockComposer_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - request image.ComposeRequest
func (_e *MockComposer_Expecter) Build(ctx any, request any) *MockComposer_Build_Call {
	return &MockComposer_Build_Call{Call: _e.mock.On("Build", ctx, request)}
}

func (_c *MockComposer_Build_Call) Run(run func(ctx context.Context, request image.ComposeRequest)) *MockComposer_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.ComposeRequest
		if args[1] != nil {
			arg1 = args[1].(image.ComposeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComposer_Build_Call) Return(err error) *MockComposer_Build_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComposer_Build_Call) RunAndReturn(run func(ctx context.Context, request image.ComposeRequest) error) *MockComposer_Build_Call {
	_c.Call.Return(run)
	return _c
}
