// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockAttestor creates a new instance of MockAttestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttestor {
	mock := &MockAttestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttestor is an autogenerated mock type for the Attestor type
type MockAttestor struct {
	mock.Mock
}

type MockAttestor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttestor) EXPECT() *MockAttestor_Expecter {
	return &MockAttestor_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockAttestor
func (_mock *MockAttestor) Verify(ctx context.Context, request pkgrepo.AttestationRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.AttestationRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAttestor_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAttestor_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.AttestationRequest
func (_e *MockAttestor_Expecter) Verify(ctx any, request any) *MockAttestor_Verify_Call {
	return &MockAttestor_Verify_Call{Call: _e.mock.On("Verify", ctx, request)}
}

func (_c *MockAttestor_Verify_Call) Run(run func(ctx context.Context, request pkgrepo.AttestationRequest)) *MockAttestor_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.AttestationRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.AttestationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestor_Verify_Call) Return(err error) *MockAttestor_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAttestor_Verify_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.AttestationRequest) error) *MockAttestor_Verify_Call {
	_c.Call.Return(run)
	return _c
}
