// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pubgh"
)

// NewMockArtifactMeta creates a new instance of MockArtifactMeta. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtifactMeta(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtifactMeta {
	mock := &MockArtifactMeta{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtifactMeta is an autogenerated mock type for the ArtifactMeta type
type MockArtifactMeta struct {
	mock.Mock
}

type MockArtifactMeta_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtifactMeta) EXPECT() *MockArtifactMeta_Expecter {
	return &MockArtifactMeta_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockArtifactMeta
func (_mock *MockArtifactMeta) Get(ctx context.Context, repository pubgh.Repository, id pubgh.ArtifactID) (pubgh.ArtifactMetadata, error) {
	ret := _mock.Called(ctx, repository, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 pubgh.ArtifactMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ArtifactID) (pubgh.ArtifactMetadata, error)); ok {
		return returnFunc(ctx, repository, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, pubgh.ArtifactID) pubgh.ArtifactMetadata); ok {
		r0 = returnFunc(ctx, repository, id)
	} else {
		r0 = ret.Get(0).(pubgh.ArtifactMetadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pubgh.Repository, pubgh.ArtifactID) error); ok {
		r1 = returnFunc(ctx, repository, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtifactMeta_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockArtifactMeta_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubgh.Repository
//   - id pubgh.ArtifactID
func (_e *MockArtifactMeta_Expecter) Get(ctx any, repository any, id any) *MockArtifactMeta_Get_Call {
	return &MockArtifactMeta_Get_Call{Call: _e.mock.On("Get", ctx, repository, id)}
}

func (_c *MockArtifactMeta_Get_Call) Run(run func(ctx context.Context, repository pubgh.Repository, id pubgh.ArtifactID)) *MockArtifactMeta_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubgh.Repository
		if args[1] != nil {
			arg1 = args[1].(pubgh.Repository)
		}
		var arg2 pubgh.ArtifactID
		if args[2] != nil {
			arg2 = args[2].(pubgh.ArtifactID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArtifactMeta_Get_Call) Return(artifactMetadata pubgh.ArtifactMetadata, err error) *MockArtifactMeta_Get_Call {
	_c.Call.Return(artifactMetadata, err)
	return _c
}

func (_c *MockArtifactMeta_Get_Call) RunAndReturn(run func(ctx context.Context, repository pubgh.Repository, id pubgh.ArtifactID) (pubgh.ArtifactMetadata, error)) *MockArtifactMeta_Get_Call {
	_c.Call.Return(run)
	return _c
}
