// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockPackageRepositoryPublisher creates a new instance of MockPackageRepositoryPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageRepositoryPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageRepositoryPublisher {
	mock := &MockPackageRepositoryPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPackageRepositoryPublisher is an autogenerated mock type for the PackageRepositoryPublisher type
type MockPackageRepositoryPublisher struct {
	mock.Mock
}

type MockPackageRepositoryPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageRepositoryPublisher) EXPECT() *MockPackageRepositoryPublisher_Expecter {
	return &MockPackageRepositoryPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPackageRepositoryPublisher
func (_mock *MockPackageRepositoryPublisher) Publish(ctx context.Context, input pkgrepo.PublishInput) (pkgrepo.PublishResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 pkgrepo.PublishResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.PublishInput) (pkgrepo.PublishResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.PublishInput) pkgrepo.PublishResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(pkgrepo.PublishResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pkgrepo.PublishInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageRepositoryPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPackageRepositoryPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - input pkgrepo.PublishInput
func (_e *MockPackageRepositoryPublisher_Expecter) Publish(ctx any, input any) *MockPackageRepositoryPublisher_Publish_Call {
	return &MockPackageRepositoryPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, input)}
}

func (_c *MockPackageRepositoryPublisher_Publish_Call) Run(run func(ctx context.Context, input pkgrepo.PublishInput)) *MockPackageRepositoryPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.PublishInput
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.PublishInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPackageRepositoryPublisher_Publish_Call) Return(publishResult pkgrepo.PublishResult, err error) *MockPackageRepositoryPublisher_Publish_Call {
	_c.Call.Return(publishResult, err)
	return _c
}

func (_c *MockPackageRepositoryPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, input pkgrepo.PublishInput) (pkgrepo.PublishResult, error)) *MockPackageRepositoryPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
