// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// ClearSign provides a mock function for the type MockSigner
func (_mock *MockSigner) ClearSign(ctx context.Context, request pkgrepo.SignRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ClearSign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.SignRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSigner_ClearSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSign'
type MockSigner_ClearSign_Call struct {
	*mock.Call
}

// ClearSign is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.SignRequest
func (_e *MockSigner_Expecter) ClearSign(ctx any, request any) *MockSigner_ClearSign_Call {
	return &MockSigner_ClearSign_Call{Call: _e.mock.On("ClearSign", ctx, request)}
}

func (_c *MockSigner_ClearSign_Call) Run(run func(ctx context.Context, request pkgrepo.SignRequest)) *MockSigner_ClearSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.SignRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.SignRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSigner_ClearSign_Call) Return(err error) *MockSigner_ClearSign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSigner_ClearSign_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.SignRequest) error) *MockSigner_ClearSign_Call {
	_c.Call.Return(run)
	return _c
}

// DetachSign provides a mock function for the type MockSigner
func (_mock *MockSigner) DetachSign(ctx context.Context, request pkgrepo.SignRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DetachSign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.SignRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSigner_DetachSign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachSign'
type MockSigner_DetachSign_Call struct {
	*mock.Call
}

// DetachSign is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.SignRequest
func (_e *MockSigner_Expecter) DetachSign(ctx any, request any) *MockSigner_DetachSign_Call {
	return &MockSigner_DetachSign_Call{Call: _e.mock.On("DetachSign", ctx, request)}
}

func (_c *MockSigner_DetachSign_Call) Run(run func(ctx context.Context, request pkgrepo.SignRequest)) *MockSigner_DetachSign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.SignRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.SignRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSigner_DetachSign_Call) Return(err error) *MockSigner_DetachSign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSigner_DetachSign_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.SignRequest) error) *MockSigner_DetachSign_Call {
	_c.Call.Return(run)
	return _c
}
