package:
  name: example
  version: ${{vars.version}}
  epoch: 0
  description: Example Go command using the Meigma release workflows.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: LicenseRef-Proprietary

vars:
  version: 0.0.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

pipeline:
  - runs: |
      install -Dm755 -o 0 -g 0 application "${{targets.destdir}}/usr/bin/example"
