// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockInspector creates a new instance of MockInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInspector {
	mock := &MockInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInspector is an autogenerated mock type for the Inspector type
type MockInspector struct {
	mock.Mock
}

type MockInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInspector) EXPECT() *MockInspector_Expecter {
	return &MockInspector_Expecter{mock: &_m.Mock}
}

// Inspect provides a mock function for the type MockInspector
func (_mock *MockInspector) Inspect(ctx context.Context, format pkgrepo.Format, packagePath string) (pkgrepo.PackageMetadata, error) {
	ret := _mock.Called(ctx, format, packagePath)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 pkgrepo.PackageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.Format, string) (pkgrepo.PackageMetadata, error)); ok {
		return returnFunc(ctx, format, packagePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.Format, string) pkgrepo.PackageMetadata); ok {
		r0 = returnFunc(ctx, format, packagePath)
	} else {
		r0 = ret.Get(0).(pkgrepo.PackageMetadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pkgrepo.Format, string) error); ok {
		r1 = returnFunc(ctx, format, packagePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInspector_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockInspector_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - format pkgrepo.Format
//   - packagePath string
func (_e *MockInspector_Expecter) Inspect(ctx any, format any, packagePath any) *MockInspector_Inspect_Call {
	return &MockInspector_Inspect_Call{Call: _e.mock.On("Inspect", ctx, format, packagePath)}
}

func (_c *MockInspector_Inspect_Call) Run(run func(ctx context.Context, format pkgrepo.Format, packagePath string)) *MockInspector_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.Format
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.Format)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInspector_Inspect_Call) Return(packageMetadata pkgrepo.PackageMetadata, err error) *MockInspector_Inspect_Call {
	_c.Call.Return(packageMetadata, err)
	return _c
}

func (_c *MockInspector_Inspect_Call) RunAndReturn(run func(ctx context.Context, format pkgrepo.Format, packagePath string) (pkgrepo.PackageMetadata, error)) *MockInspector_Inspect_Call {
	_c.Call.Return(run)
	return _c
}
