// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage/pubgh"
)

// NewMockAssetReplacer creates a new instance of MockAssetReplacer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetReplacer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetReplacer {
	mock := &MockAssetReplacer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetReplacer is an autogenerated mock type for the AssetReplacer type
type MockAssetReplacer struct {
	mock.Mock
}

type MockAssetReplacer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetReplacer) EXPECT() *MockAssetReplacer_Expecter {
	return &MockAssetReplacer_Expecter{mock: &_m.Mock}
}

// Replace provides a mock function for the type MockAssetReplacer
func (_mock *MockAssetReplacer) Replace(ctx context.Context, repository pubgh.Repository, tag rel.Tag, expected []pubgh.AssetPath) error {
	ret := _mock.Called(ctx, repository, tag, expected)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pubgh.Repository, rel.Tag, []pubgh.AssetPath) error); ok {
		r0 = returnFunc(ctx, repository, tag, expected)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssetReplacer_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockAssetReplacer_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - repository pubgh.Repository
//   - tag rel.Tag
//   - expected []pubgh.AssetPath
func (_e *MockAssetReplacer_Expecter) Replace(ctx any, repository any, tag any, expected any) *MockAssetReplacer_Replace_Call {
	return &MockAssetReplacer_Replace_Call{Call: _e.mock.On("Replace", ctx, repository, tag, expected)}
}

func (_c *MockAssetReplacer_Replace_Call) Run(run func(ctx context.Context, repository pubgh.Repository, tag rel.Tag, expected []pubgh.AssetPath)) *MockAssetReplacer_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pubgh.Repository
		if args[1] != nil {
			arg1 = args[1].(pubgh.Repository)
		}
		var arg2 rel.Tag
		if args[2] != nil {
			arg2 = args[2].(rel.Tag)
		}
		var arg3 []pubgh.AssetPath
		if args[3] != nil {
			arg3 = args[3].([]pubgh.AssetPath)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAssetReplacer_Replace_Call) Return(err error) *MockAssetReplacer_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssetReplacer_Replace_Call) RunAndReturn(run func(ctx context.Context, repository pubgh.Repository, tag rel.Tag, expected []pubgh.AssetPath) error) *MockAssetReplacer_Replace_Call {
	_c.Call.Return(run)
	return _c
}
