// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockStore
func (_mock *MockStore) Download(ctx context.Context, name string, destination io.Writer) (pkgrepo.StoredContent, error) {
	ret := _mock.Called(ctx, name, destination)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 pkgrepo.StoredContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) (pkgrepo.StoredContent, error)); ok {
		return returnFunc(ctx, name, destination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Writer) pkgrepo.StoredContent); ok {
		r0 = returnFunc(ctx, name, destination)
	} else {
		r0 = ret.Get(0).(pkgrepo.StoredContent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Writer) error); ok {
		r1 = returnFunc(ctx, name, destination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStore_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - destination io.Writer
func (_e *MockStore_Expecter) Download(ctx any, name any, destination any) *MockStore_Download_Call {
	return &MockStore_Download_Call{Call: _e.mock.On("Download", ctx, name, destination)}
}

func (_c *MockStore_Download_Call) Run(run func(ctx context.Context, name string, destination io.Writer)) *MockStore_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Download_Call) Return(storedContent pkgrepo.StoredContent, err error) *MockStore_Download_Call {
	_c.Call.Return(storedContent, err)
	return _c
}

func (_c *MockStore_Download_Call) RunAndReturn(run func(ctx context.Context, name string, destination io.Writer) (pkgrepo.StoredContent, error)) *MockStore_Download_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStore
func (_mock *MockStore) List(ctx context.Context) ([]pkgrepo.StoredObject, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []pkgrepo.StoredObject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]pkgrepo.StoredObject, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []pkgrepo.StoredObject); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkgrepo.StoredObject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) List(ctx any) *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockStore_List_Call) Run(run func(ctx context.Context)) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_List_Call) Return(storedObjects []pkgrepo.StoredObject, err error) *MockStore_List_Call {
	_c.Call.Return(storedObjects, err)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]pkgrepo.StoredObject, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockStore
func (_mock *MockStore) Stat(ctx context.Context, name string) (pkgrepo.StoredContent, bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 pkgrepo.StoredContent
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pkgrepo.StoredContent, bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pkgrepo.StoredContent); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(pkgrepo.StoredContent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStore_Expecter) Stat(ctx any, name any) *MockStore_Stat_Call {
	return &MockStore_Stat_Call{Call: _e.mock.On("Stat", ctx, name)}
}

func (_c *MockStore_Stat_Call) Run(run func(ctx context.Context, name string)) *MockStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Stat_Call) Return(storedContent pkgrepo.StoredContent, b bool, err error) *MockStore_Stat_Call {
	_c.Call.Return(storedContent, b, err)
	return _c
}

func (_c *MockStore_Stat_Call) RunAndReturn(run func(ctx context.Context, name string) (pkgrepo.StoredContent, bool, error)) *MockStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockStore
func (_mock *MockStore) Upload(ctx context.Context, request pkgrepo.UploadRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.UploadRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.UploadRequest
func (_e *MockStore_Expecter) Upload(ctx any, request any) *MockStore_Upload_Call {
	return &MockStore_Upload_Call{Call: _e.mock.On("Upload", ctx, request)}
}

func (_c *MockStore_Upload_Call) Run(run func(ctx context.Context, request pkgrepo.UploadRequest)) *MockStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.UploadRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.UploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Upload_Call) Return(err error) *MockStore_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Upload_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.UploadRequest) error) *MockStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}
