// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/puboci"
)

// NewMockContentPusher creates a new instance of MockContentPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentPusher {
	mock := &MockContentPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentPusher is an autogenerated mock type for the ContentPusher type
type MockContentPusher struct {
	mock.Mock
}

type MockContentPusher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentPusher) EXPECT() *MockContentPusher_Expecter {
	return &MockContentPusher_Expecter{mock: &_m.Mock}
}

// PushBlob provides a mock function for the type MockContentPusher
func (_mock *MockContentPusher) PushBlob(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader) error {
	ret := _mock.Called(ctx, image, descriptor, content)

	if len(ret) == 0 {
		panic("no return value specified for PushBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Image, puboci.Descriptor, io.Reader) error); ok {
		r0 = returnFunc(ctx, image, descriptor, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentPusher_PushBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushBlob'
type MockContentPusher_PushBlob_Call struct {
	*mock.Call
}

// PushBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - image puboci.Image
//   - descriptor puboci.Descriptor
//   - content io.Reader
func (_e *MockContentPusher_Expecter) PushBlob(ctx any, image any, descriptor any, content any) *MockContentPusher_PushBlob_Call {
	return &MockContentPusher_PushBlob_Call{Call: _e.mock.On("PushBlob", ctx, image, descriptor, content)}
}

func (_c *MockContentPusher_PushBlob_Call) Run(run func(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader)) *MockContentPusher_PushBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.Image
		if args[1] != nil {
			arg1 = args[1].(puboci.Image)
		}
		var arg2 puboci.Descriptor
		if args[2] != nil {
			arg2 = args[2].(puboci.Descriptor)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentPusher_PushBlob_Call) Return(err error) *MockContentPusher_PushBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentPusher_PushBlob_Call) RunAndReturn(run func(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader) error) *MockContentPusher_PushBlob_Call {
	_c.Call.Return(run)
	return _c
}

// PushManifest provides a mock function for the type MockContentPusher
func (_mock *MockContentPusher) PushManifest(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader) error {
	ret := _mock.Called(ctx, image, descriptor, content)

	if len(ret) == 0 {
		panic("no return value specified for PushManifest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Image, puboci.Descriptor, io.Reader) error); ok {
		r0 = returnFunc(ctx, image, descriptor, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentPusher_PushManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushManifest'
type MockContentPusher_PushManifest_Call struct {
	*mock.Call
}

// PushManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - image puboci.Image
//   - descriptor puboci.Descriptor
//   - content io.Reader
func (_e *MockContentPusher_Expecter) PushManifest(ctx any, image any, descriptor any, content any) *MockContentPusher_PushManifest_Call {
	return &MockContentPusher_PushManifest_Call{Call: _e.mock.On("PushManifest", ctx, image, descriptor, content)}
}

func (_c *MockContentPusher_PushManifest_Call) Run(run func(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader)) *MockContentPusher_PushManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.Image
		if args[1] != nil {
			arg1 = args[1].(puboci.Image)
		}
		var arg2 puboci.Descriptor
		if args[2] != nil {
			arg2 = args[2].(puboci.Descriptor)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentPusher_PushManifest_Call) Return(err error) *MockContentPusher_PushManifest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentPusher_PushManifest_Call) RunAndReturn(run func(ctx context.Context, image puboci.Image, descriptor puboci.Descriptor, content io.Reader) error) *MockContentPusher_PushManifest_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockContentPusher
func (_mock *MockContentPusher) Verify(ctx context.Context, ref puboci.DigestRef) error {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.DigestRef) error); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentPusher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockContentPusher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - ref puboci.DigestRef
func (_e *MockContentPusher_Expecter) Verify(ctx any, ref any) *MockContentPusher_Verify_Call {
	return &MockContentPusher_Verify_Call{Call: _e.mock.On("Verify", ctx, ref)}
}

func (_c *MockContentPusher_Verify_Call) Run(run func(ctx context.Context, ref puboci.DigestRef)) *MockContentPusher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.DigestRef
		if args[1] != nil {
			arg1 = args[1].(puboci.DigestRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentPusher_Verify_Call) Return(err error) *MockContentPusher_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentPusher_Verify_Call) RunAndReturn(run func(ctx context.Context, ref puboci.DigestRef) error) *MockContentPusher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
