// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage/puboci"
)

// NewMockStateReader creates a new instance of MockStateReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateReader {
	mock := &MockStateReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateReader is an autogenerated mock type for the StateReader type
type MockStateReader struct {
	mock.Mock
}

type MockStateReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateReader) EXPECT() *MockStateReader_Expecter {
	return &MockStateReader_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockStateReader
func (_mock *MockStateReader) Resolve(ctx context.Context, ref puboci.Reference) (rel.Digest, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 rel.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Reference) (rel.Digest, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Reference) rel.Digest); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(rel.Digest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, puboci.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateReader_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockStateReader_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - ref puboci.Reference
func (_e *MockStateReader_Expecter) Resolve(ctx any, ref any) *MockStateReader_Resolve_Call {
	return &MockStateReader_Resolve_Call{Call: _e.mock.On("Resolve", ctx, ref)}
}

func (_c *MockStateReader_Resolve_Call) Run(run func(ctx context.Context, ref puboci.Reference)) *MockStateReader_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.Reference
		if args[1] != nil {
			arg1 = args[1].(puboci.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateReader_Resolve_Call) Return(digest rel.Digest, err error) *MockStateReader_Resolve_Call {
	_c.Call.Return(digest, err)
	return _c
}

func (_c *MockStateReader_Resolve_Call) RunAndReturn(run func(ctx context.Context, ref puboci.Reference) (rel.Digest, error)) *MockStateReader_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockStateReader
func (_mock *MockStateReader) Version(ctx context.Context, ref puboci.Reference) (rel.Version, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 rel.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Reference) (rel.Version, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Reference) rel.Version); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(rel.Version)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, puboci.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateReader_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockStateReader_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
//   - ref puboci.Reference
func (_e *MockStateReader_Expecter) Version(ctx any, ref any) *MockStateReader_Version_Call {
	return &MockStateReader_Version_Call{Call: _e.mock.On("Version", ctx, ref)}
}

func (_c *MockStateReader_Version_Call) Run(run func(ctx context.Context, ref puboci.Reference)) *MockStateReader_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.Reference
		if args[1] != nil {
			arg1 = args[1].(puboci.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateReader_Version_Call) Return(version rel.Version, err error) *MockStateReader_Version_Call {
	_c.Call.Return(version, err)
	return _c
}

func (_c *MockStateReader_Version_Call) RunAndReturn(run func(ctx context.Context, ref puboci.Reference) (rel.Version, error)) *MockStateReader_Version_Call {
	_c.Call.Return(run)
	return _c
}
