// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage/puboci"
)

// NewMockTagCommitter creates a new instance of MockTagCommitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagCommitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagCommitter {
	mock := &MockTagCommitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagCommitter is an autogenerated mock type for the TagCommitter type
type MockTagCommitter struct {
	mock.Mock
}

type MockTagCommitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagCommitter) EXPECT() *MockTagCommitter_Expecter {
	return &MockTagCommitter_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockTagCommitter
func (_mock *MockTagCommitter) Commit(ctx context.Context, image puboci.Image, digest rel.Digest, tags []rel.Tag) error {
	ret := _mock.Called(ctx, image, digest, tags)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.Image, rel.Digest, []rel.Tag) error); ok {
		r0 = returnFunc(ctx, image, digest, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagCommitter_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTagCommitter_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - image puboci.Image
//   - digest rel.Digest
//   - tags []rel.Tag
func (_e *MockTagCommitter_Expecter) Commit(ctx any, image any, digest any, tags any) *MockTagCommitter_Commit_Call {
	return &MockTagCommitter_Commit_Call{Call: _e.mock.On("Commit", ctx, image, digest, tags)}
}

func (_c *MockTagCommitter_Commit_Call) Run(run func(ctx context.Context, image puboci.Image, digest rel.Digest, tags []rel.Tag)) *MockTagCommitter_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.Image
		if args[1] != nil {
			arg1 = args[1].(puboci.Image)
		}
		var arg2 rel.Digest
		if args[2] != nil {
			arg2 = args[2].(rel.Digest)
		}
		var arg3 []rel.Tag
		if args[3] != nil {
			arg3 = args[3].([]rel.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTagCommitter_Commit_Call) Return(err error) *MockTagCommitter_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagCommitter_Commit_Call) RunAndReturn(run func(ctx context.Context, image puboci.Image, digest rel.Digest, tags []rel.Tag) error) *MockTagCommitter_Commit_Call {
	_c.Call.Return(run)
	return _c
}
