package pkgrepo

import (
	"fmt"
	"io"
	"net/url"
	"os"
	"path"
	"regexp"
	"strings"
	"time"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage"
)

const (
	// PublishStatePublished reports that at least one repository object was written.
	PublishStatePublished PublishState = "published"
	// PublishStateUnchanged reports that every requested object already matched.
	PublishStateUnchanged PublishState = "unchanged"
)

var (
	// workflowPattern accepts one GitHub Actions workflow at the required repository location.
	workflowPattern = regexp.MustCompile(`^\.github/workflows/[A-Za-z0-9][A-Za-z0-9._-]*\.ya?ml$`)
	// commitPattern accepts one full lowercase Git commit SHA.
	commitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)
)

// PublishState is the converged remote repository state.
type PublishState string

// ChecksumIdentity is one exact Cosign certificate identity URL.
type ChecksumIdentity string

// AttestationSigner is one GitHub attestation signer workflow.
type AttestationSigner string

// SourcePolicy binds one producer to explicit shared-workflow trust identities.
type SourcePolicy struct {
	// Repository is the allowlisted producer repository.
	Repository Repository
	// ChecksumIdentity is the exact Cosign certificate identity that signs checksums.txt.
	ChecksumIdentity ChecksumIdentity
	// AttestationSigner is the GitHub workflow that attests release payloads.
	AttestationSigner AttestationSigner
}

// PublicationConfig is the complete reviewed package-repository publication policy.
type PublicationConfig struct {
	// Repository configures local package ownership, keys, and repository layout.
	Repository Config
	// Origin is the HTTPS public repository root used for post-publication installs.
	Origin string
	// Sources binds every configured producer to trusted GitHub workflow identities.
	Sources []SourcePolicy
}

// ReleaseRequest identifies one exact public GitHub Release.
type ReleaseRequest struct {
	// Repository is the canonical producer owner/name.
	Repository Repository
	// Tag is the exact stable release tag.
	Tag string
}

// ReleaseAsset is one fully downloaded public GitHub Release asset.
type ReleaseAsset struct {
	// Name is the validated flat GitHub Release asset name.
	Name stage.AssetName
	// Path is the destination-root-relative downloaded file path.
	Path string
	// Digest is the GitHub-advertised and locally verified SHA-256 digest.
	Digest rel.Digest
	// Size is the verified asset size in bytes.
	Size int64
}

// Release is one exact public release downloaded into a confined destination.
type Release struct {
	// Repository is the canonical producer repository.
	Repository Repository
	// Tag is the exact release tag.
	Tag string
	// Commit is the full commit SHA resolved from the tag ref.
	Commit string
	// PublishedAt is GitHub's release publication time.
	PublishedAt time.Time
	// Assets contains every release asset in lexical name order.
	Assets []ReleaseAsset
}

// AttestationRequest binds one downloaded package to its expected GitHub provenance.
type AttestationRequest struct {
	// Path is the absolute local package path.
	Path string
	// Repository is the source owner/name used for attestation lookup.
	Repository Repository
	// SourceRef is the exact refs/tags/... source ref.
	SourceRef string
	// SourceDigest is the full source commit SHA.
	SourceDigest string
	// SignerWorkflow is the trusted GitHub attestation signer workflow.
	SignerWorkflow AttestationSigner
}

// StoredObject is one object discovered in repository storage.
type StoredObject struct {
	// Path is the slash-separated bucket-relative object key.
	Path string
	// Size is the remote content length in bytes.
	Size int64
}

// StoredContent describes one downloaded or statted storage object.
type StoredContent struct {
	// Digest is the SHA-256 value stored in object custom metadata.
	Digest rel.Digest
	// Size is the remote content length in bytes.
	Size int64
}

// UploadRequest describes one generated repository object write.
type UploadRequest struct {
	// Path is the slash-separated bucket-relative object key.
	Path string
	// Body streams the exact generated bytes.
	Body io.Reader
	// Digest is the SHA-256 value recorded in object custom metadata.
	Digest rel.Digest
	// Size is the exact body length in bytes.
	Size int64
	// Cache is the public cache policy selected by the repository engine.
	Cache CachePolicy
}

// InstallRequest describes one native package-manager verification pass.
type InstallRequest struct {
	// Root is the generated local repository root for a pre-publication check.
	// Nil selects the public Origin instead.
	Root *os.Root
	// Keys is the reviewed local public-key root mounted read-only by clients.
	Keys *os.Root
	// Origin is the HTTPS repository root for a post-publication check.
	Origin string
	// Channel is the repository channel to install from.
	Channel Channel
	// Packages is the requested producer's complete package-name allowlist.
	Packages []PackageName
	// Version is the exact release version expected after installation.
	Version rel.Version
	// APTKey is the aggregate APT public-key source path beneath Keys.
	APTKey string
	// RPMKeys contains the aggregate metadata key followed by producer package keys.
	RPMKeys []string
	// APKKeys contains the aggregate index key followed by producer package keys.
	APKKeys []string
}

// PublishInput supplies reviewed policy and confined scratch roots for one publication.
type PublishInput struct {
	// Config is the complete reviewed publication policy.
	Config PublicationConfig
	// Request identifies the producer release to publish.
	Request Request
	// Keys confines the checked-in public key files named by Config.
	Keys *os.Root
	// Source is an empty scratch root for downloaded and mirrored package inputs.
	Source *os.Root
	// Work is an empty scratch root for package inspection and verification.
	Work *os.Root
	// Output is an empty scratch root for the generated public repository tree.
	Output *os.Root
}

// PublishResult reports the converged publication state.
type PublishResult struct {
	// State is published when objects were written and unchanged otherwise.
	State PublishState `json:"state"`
	// Repository is the producer repository that supplied the requested release.
	Repository Repository `json:"repository"`
	// Tag is the exact published release tag.
	Tag string `json:"tag"`
	// Artifacts is the complete generated repository object count.
	Artifacts int `json:"artifacts"`
	// Uploaded is the number of objects written during this invocation.
	Uploaded int `json:"uploaded"`
}

// Validate checks the complete reviewed publication configuration.
func (c PublicationConfig) Validate() error {
	if err := c.Repository.Validate(); err != nil {
		return fmt.Errorf("repository: %w", err)
	}
	if err := validateOrigin(c.Origin); err != nil {
		return err
	}
	if len(c.Sources) != len(c.Repository.Producers) {
		return fmt.Errorf(
			"source policy count %d does not match producer count %d",
			len(c.Sources),
			len(c.Repository.Producers),
		)
	}

	seen := make(map[Repository]struct{}, len(c.Sources))
	for index, policy := range c.Sources {
		if err := policy.Validate(); err != nil {
			return fmt.Errorf("source policy %d: %w", index, err)
		}
		if _, exists := seen[policy.Repository]; exists {
			return fmt.Errorf("source repository %q is duplicated", policy.Repository)
		}
		seen[policy.Repository] = struct{}{}
	}
	for _, producer := range c.Repository.Producers {
		if _, exists := seen[producer.Repository]; !exists {
			return fmt.Errorf("producer %q has no source policy", producer.Repository)
		}
	}

	return nil
}

// PolicyFor returns the unique source policy for repository.
func (c PublicationConfig) PolicyFor(repository Repository) (SourcePolicy, error) {
	for _, policy := range c.Sources {
		if policy.Repository == repository {
			return policy, nil
		}
	}

	return SourcePolicy{}, fmt.Errorf("repository %q is not allowlisted", repository)
}

// ProducerFor returns the unique local producer configuration for repository.
func (c PublicationConfig) ProducerFor(repository Repository) (Producer, error) {
	for _, producer := range c.Repository.Producers {
		if producer.Repository == repository {
			return producer, nil
		}
	}

	return Producer{}, fmt.Errorf("repository %q is not allowlisted", repository)
}

// Validate checks one source verification policy.
func (p SourcePolicy) Validate() error {
	if _, err := ParseRepository(string(p.Repository)); err != nil {
		return err
	}
	if _, err := ParseChecksumIdentity(string(p.ChecksumIdentity)); err != nil {
		return err
	}
	if _, err := ParseAttestationSigner(string(p.AttestationSigner)); err != nil {
		return err
	}

	return nil
}

// ParseChecksumIdentity validates one exact Cosign certificate identity.
//
// The identity must be
// https://github.com/<owner>/<repo>/.github/workflows/<file>@<40-character-sha>
// with a lowercase owner and repository. Branches, tags, missing refs,
// credentials, queries, fragments, and non-GitHub hosts are rejected.
func ParseChecksumIdentity(value string) (ChecksumIdentity, error) {
	parsed, err := url.Parse(value)
	if err != nil {
		return "", fmt.Errorf("checksum identity %q is invalid: %w", value, err)
	}
	if parsed.Scheme != "https" || parsed.Host == "" {
		return "", fmt.Errorf("checksum identity %q must be an absolute HTTPS URL", value)
	}
	if parsed.Host != "github.com" {
		return "", fmt.Errorf("checksum identity %q must use host github.com", value)
	}
	if parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return "", fmt.Errorf("checksum identity %q must not contain credentials, a query, or a fragment", value)
	}

	pathAndRef := strings.TrimPrefix(parsed.EscapedPath(), "/")
	workflowPath, ref, found := strings.Cut(pathAndRef, "@")
	if !found || ref == "" {
		return "", fmt.Errorf("checksum identity %q is missing an immutable commit SHA", value)
	}
	if !commitPattern.MatchString(ref) {
		return "", fmt.Errorf("checksum identity %q must pin a full lowercase commit SHA", value)
	}
	repository, workflow, ok := splitOwnerWorkflow(workflowPath)
	if !ok {
		return "", fmt.Errorf("checksum identity %q is not a GitHub workflow identity", value)
	}
	if _, parseErr := ParseRepository(repository); parseErr != nil {
		return "", fmt.Errorf("checksum identity %q: %w", value, parseErr)
	}
	if !workflowPattern.MatchString(workflow) {
		return "", fmt.Errorf("checksum identity %q has an invalid workflow path", value)
	}
	canonical := "https://github.com/" + repository + "/" + workflow + "@" + ref
	if value != canonical {
		return "", fmt.Errorf("checksum identity %q is invalid", value)
	}

	return ChecksumIdentity(value), nil
}

// ParseAttestationSigner validates one GitHub attestation signer workflow.
//
// The signer must be <owner>/<repo>/.github/workflows/<file> with a lowercase
// owner and repository. URLs, refs, credentials, and relative paths are rejected.
func ParseAttestationSigner(value string) (AttestationSigner, error) {
	if strings.Contains(value, "://") || strings.ContainsAny(value, "?#@") {
		return "", fmt.Errorf(
			"attestation signer %q must be owner/repository/.github/workflows/<file>",
			value,
		)
	}
	repository, workflow, ok := splitOwnerWorkflow(value)
	if !ok {
		return "", fmt.Errorf(
			"attestation signer %q must be owner/repository/.github/workflows/<file>",
			value,
		)
	}
	if _, err := ParseRepository(repository); err != nil {
		return "", fmt.Errorf("attestation signer %q: %w", value, err)
	}
	if !workflowPattern.MatchString(workflow) {
		return "", fmt.Errorf("attestation signer %q has an invalid workflow path", value)
	}
	canonical := repository + "/" + workflow
	if value != canonical {
		return "", fmt.Errorf("attestation signer %q is invalid", value)
	}

	return AttestationSigner(value), nil
}

// splitOwnerWorkflow splits owner/name/.github/workflows/<file> into repository and workflow path.
func splitOwnerWorkflow(value string) (string, string, bool) {
	const marker = "/.github/workflows/"
	repository, file, found := strings.Cut(value, marker)
	if !found || repository == "" || file == "" || strings.Contains(file, "/") {
		return "", "", false
	}

	return repository, ".github/workflows/" + file, true
}

// Validate checks one downloaded release and its exact source binding.
func (r Release) Validate(request ReleaseRequest) error {
	if r.Repository != request.Repository {
		return fmt.Errorf("release repository %q does not match request %q", r.Repository, request.Repository)
	}
	if r.Tag != request.Tag {
		return fmt.Errorf("release tag %q does not match request %q", r.Tag, request.Tag)
	}
	if !commitPattern.MatchString(r.Commit) {
		return fmt.Errorf("release commit %q is not a full lowercase SHA", r.Commit)
	}
	if r.PublishedAt.IsZero() {
		return fmt.Errorf("release %s has no publication time", r.Tag)
	}
	if len(r.Assets) == 0 {
		return fmt.Errorf("release %s has no assets", r.Tag)
	}

	seen := make(map[stage.AssetName]struct{}, len(r.Assets))
	for _, asset := range r.Assets {
		if _, err := stage.ParseAssetName(asset.Name.String()); err != nil {
			return fmt.Errorf("release asset: %w", err)
		}
		if _, exists := seen[asset.Name]; exists {
			return fmt.Errorf("release asset %q is duplicated", asset.Name)
		}
		seen[asset.Name] = struct{}{}
		if asset.Path == "" || path.IsAbs(asset.Path) || path.Clean(asset.Path) != asset.Path ||
			strings.HasPrefix(asset.Path, "../") {
			return fmt.Errorf("release asset %q path %q is not confined", asset.Name, asset.Path)
		}
		if _, err := rel.ParseDigest(asset.Digest.String()); err != nil {
			return fmt.Errorf("release asset %q digest: %w", asset.Name, err)
		}
		if asset.Size < 0 {
			return fmt.Errorf("release asset %q size %d is negative", asset.Name, asset.Size)
		}
	}

	return nil
}

// validateOrigin checks one absolute HTTPS repository root without credentials or a path prefix.
func validateOrigin(value string) error {
	parsed, err := url.Parse(value)
	if err != nil {
		return fmt.Errorf("origin %q: %w", value, err)
	}
	if parsed.Scheme != "https" || parsed.Host == "" {
		return fmt.Errorf("origin %q must be an absolute HTTPS URL", value)
	}
	if parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return fmt.Errorf("origin %q must not contain credentials, a query, or a fragment", value)
	}
	if parsed.EscapedPath() != "" && parsed.EscapedPath() != "/" {
		return fmt.Errorf("origin %q must not contain a path prefix", value)
	}

	return nil
}

// packageObjectFormat returns the native format encoded by one canonical package object path.
func packageObjectFormat(name string, channel Channel) (Format, bool) {
	clean := path.Clean(name)
	if clean != name || path.IsAbs(name) || strings.HasPrefix(name, "../") {
		return "", false
	}
	if strings.HasPrefix(name, "apt/pool/main/") && strings.HasSuffix(name, ".deb") {
		return FormatDEB, true
	}
	channelName := string(channel)
	if strings.HasPrefix(name, path.Join("rpm", channelName)+"/") &&
		strings.Contains(name, "/packages/") && strings.HasSuffix(name, ".rpm") {
		return FormatRPM, true
	}
	if strings.HasPrefix(name, path.Join("apk", channelName, "main")+"/") && strings.HasSuffix(name, ".apk") {
		return FormatAPK, true
	}

	return "", false
}
