// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/puboci"
)

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// SignRecursive provides a mock function for the type MockSigner
func (_mock *MockSigner) SignRecursive(ctx context.Context, ref puboci.DigestRef) error {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for SignRecursive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, puboci.DigestRef) error); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSigner_SignRecursive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignRecursive'
type MockSigner_SignRecursive_Call struct {
	*mock.Call
}

// SignRecursive is a helper method to define mock.On call
//   - ctx context.Context
//   - ref puboci.DigestRef
func (_e *MockSigner_Expecter) SignRecursive(ctx any, ref any) *MockSigner_SignRecursive_Call {
	return &MockSigner_SignRecursive_Call{Call: _e.mock.On("SignRecursive", ctx, ref)}
}

func (_c *MockSigner_SignRecursive_Call) Run(run func(ctx context.Context, ref puboci.DigestRef)) *MockSigner_SignRecursive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 puboci.DigestRef
		if args[1] != nil {
			arg1 = args[1].(puboci.DigestRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSigner_SignRecursive_Call) Return(err error) *MockSigner_SignRecursive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSigner_SignRecursive_Call) RunAndReturn(run func(ctx context.Context, ref puboci.DigestRef) error) *MockSigner_SignRecursive_Call {
	_c.Call.Return(run)
	return _c
}
