// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/rel"
	"github.com/meigma/release/internal/stage/pubgh"
)

// NewMockRefResolver creates a new instance of MockRefResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefResolver {
	mock := &MockRefResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefResolver is an autogenerated mock type for the RefResolver type
type MockRefResolver struct {
	mock.Mock
}

type MockRefResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefResolver) EXPECT() *MockRefResolver_Expecter {
	return &MockRefResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockRefResolver
func (_mock *MockRefResolver) Resolve(ctx context.Context, tag rel.Tag) (pubgh.CommitSHA, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 pubgh.CommitSHA
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rel.Tag) (pubgh.CommitSHA, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rel.Tag) pubgh.CommitSHA); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Get(0).(pubgh.CommitSHA)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rel.Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockRefResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - tag rel.Tag
func (_e *MockRefResolver_Expecter) Resolve(ctx any, tag any) *MockRefResolver_Resolve_Call {
	return &MockRefResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, tag)}
}

func (_c *MockRefResolver_Resolve_Call) Run(run func(ctx context.Context, tag rel.Tag)) *MockRefResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rel.Tag
		if args[1] != nil {
			arg1 = args[1].(rel.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefResolver_Resolve_Call) Return(commitSHA pubgh.CommitSHA, err error) *MockRefResolver_Resolve_Call {
	_c.Call.Return(commitSHA, err)
	return _c
}

func (_c *MockRefResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, tag rel.Tag) (pubgh.CommitSHA, error)) *MockRefResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
