// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/pkgrepo"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Verify(ctx context.Context, request pkgrepo.VerificationRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkgrepo.VerificationRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - request pkgrepo.VerificationRequest
func (_e *MockVerifier_Expecter) Verify(ctx any, request any) *MockVerifier_Verify_Call {
	return &MockVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, request)}
}

func (_c *MockVerifier_Verify_Call) Run(run func(ctx context.Context, request pkgrepo.VerificationRequest)) *MockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkgrepo.VerificationRequest
		if args[1] != nil {
			arg1 = args[1].(pkgrepo.VerificationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifier_Verify_Call) Return(err error) *MockVerifier_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, request pkgrepo.VerificationRequest) error) *MockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
