name: CI

on:
  pull_request:
    branches:
      - main
      - mvp
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    permissions:
      contents: read
    uses: ./.github/workflows/go-ci.yml
