// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/meigma/release/internal/stage/image"
)

// NewMockAPKBuilder creates a new instance of MockAPKBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPKBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPKBuilder {
	mock := &MockAPKBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPKBuilder is an autogenerated mock type for the APKBuilder type
type MockAPKBuilder struct {
	mock.Mock
}

type MockAPKBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPKBuilder) EXPECT() *MockAPKBuilder_Expecter {
	return &MockAPKBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockAPKBuilder
func (_mock *MockAPKBuilder) Build(ctx context.Context, request image.APKBuildRequest) (image.APKRepositories, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 image.APKRepositories
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.APKBuildRequest) (image.APKRepositories, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, image.APKBuildRequest) image.APKRepositories); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(image.APKRepositories)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, image.APKBuildRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPKBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockAPKBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - request image.APKBuildRequest
func (_e *MockAPKBuilder_Expecter) Build(ctx any, request any) *MockAPKBuilder_Build_Call {
	return &MockAPKBuilder_Build_Call{Call: _e.mock.On("Build", ctx, request)}
}

func (_c *MockAPKBuilder_Build_Call) Run(run func(ctx context.Context, request image.APKBuildRequest)) *MockAPKBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 image.APKBuildRequest
		if args[1] != nil {
			arg1 = args[1].(image.APKBuildRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPKBuilder_Build_Call) Return(aPKRepositories image.APKRepositories, err error) *MockAPKBuilder_Build_Call {
	_c.Call.Return(aPKRepositories, err)
	return _c
}

func (_c *MockAPKBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, request image.APKBuildRequest) (image.APKRepositories, error)) *MockAPKBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
